FROM broadinstitute/gatk:4.1.4.1

# install dependency
RUN apt-get update && \
    apt-get install -y python3-pip python3-dev software-properties-common curl wget && \
    apt-get install -y autoconf automake make gcc perl zlib1g-dev libbz2-dev liblzma-dev libcurl4-gnutls-dev libssl-dev libncurses5-dev

# install samtools
RUN wget https://github.com/samtools/samtools/releases/download/1.10/samtools-1.10.tar.bz2 -O samtools.tar.bz2 && \
    tar -xjvf samtools.tar.bz2 && \
    cd samtools-1.10 && \
    make && \
    make prefix=/usr/local/bin install

# remove old version such as 0.x from samtools and create a link to new version
RUN apt remove -y samtools && \
    ln -s /usr/local/bin/bin/samtools /usr/bin/samtools

RUN mkdir /tools

ENV PATH="/tools:${PATH}"

RUN useradd -ms /bin/bash ubuntu

CMD ["/bin/bash"]
